version = 0.1

[default.deploy.parameters]
stack_name = "rds-sam-stack"
resolve_s3 = true
s3_prefix = "rds-sam-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
